---
title: "'ruler' functional API"
author: "Evgeni Chasnovski"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette contains some thoughts about `ruler` functional API.

## General thoughts

`ruler` is yet another data validation R package. Its main goal is to provide
tools for tidy data validation report. It is designed to work tightly with
[dplyr](https://github.com/tidyverse/dplyr).

- The main data format is [tibble](https://github.com/tidyverse/tibble) because 
there will be many operations with list-columns and because of its
'tidyverseness'.

- The main function is `expose`: it exposes rule breakers in supplied data. Its
output is always the unmodified input data with possibly changed attribute
`ruler_report` (name is subject to change);

- The key concept of tidy data validation report is to __enable its__
__reproducibility__. Its format (for now) is a list with three elements:
    - `packs` - __named__ list of rule packs functions;
    - `checked_vars` - list with data about which variables were actually
      exposed;
    - `breakers` - a tibble with the data completely describing rule breakers
    (elements which don't satisfy the rule). It has the following structure:
        - `pack` - name of rules pack;
        - `rule` - name of rule;
        - `var` - name of column in which breaker is detected;
        - `id` - value of `.id` column describing the row in which particular
        breaker is detected.

## Desired use cases

After getting validation report user can do whatever he/she likes: print
its summary, use for data repairment, stop pipe execution and so on.
